# Generated by Django 5.2.13 on 2026-09-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('decision', 'Decision'), ('revision_submitted', 'Revision Submitted'), ('screening', 'Screening'), ('publication', 'Publication'), ('role', 'Role change')], default='decision', max_length=30),
        ),
    ]
