# Generated by Django 5.2.13 on 2026-09-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('decision', 'Decision'), ('revision_submitted', 'Revision Submitted'), ('screening', 'Screening'), ('review_invite', 'Review Invitation'), ('review_response', 'Review Response'), ('review_extension', 'Review Extension'), ('review_submitted', 'Review Submitted'), ('role', 'Role change')], default='decision', max_length=30),
        ),
    ]
