# Generated by Django 5.2.13 on 2026-06-03 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('author', 'Author'), ('reviewer', 'Reviewer'), ('editor', 'Editor'), ('admin', 'Admin')], default='student', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='active', max_length=20)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('student_id', models.CharField(blank=True, max_length=50)),
                ('programme', models.CharField(blank=True, max_length=255)),
                ('orcid_id', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('research_areas', models.TextField(blank=True)),
                ('expertise_areas', models.TextField(blank=True)),
                ('availability_status', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
