# Generated by Django 5.2.13 on 2026-06-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('student', 'Student'), ('author', 'Author'), ('reviewer', 'Reviewer'), ('editor', 'Editor'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
