# Generated by Django 5.2.13 on 2026-06-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_affiliation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reviewer_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.JSONField(default=list),
        ),
    ]
