# Generated by Django 5.2.13 on 2026-09-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_specialty_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorinvite',
            name='institution',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='editorinvite',
            name='orcid_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='editorinvite',
            name='specialty_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
