# Generated by Django 5.2.13 on 2026-09-15 06:50

from django.db import migrations, models


def mark_existing_blocked_accounts(apps, schema_editor):
    # Before this field existed, suspend and delete did the same thing, so an
    # account that is already blocked has no recorded reason. Deleted is the
    # closer reading: it has no end date for anything to lift automatically.
    UserProfile = apps.get_model('users', 'UserProfile')
    UserProfile.objects.filter(user__is_active=False).update(account_status='deactivated')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_repair_degree_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('deactivated', 'Deleted')], db_default='active', default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='suspended_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(mark_existing_blocked_accounts, migrations.RunPython.noop),
    ]
