# Generated by Django 5.2.13 on 2026-10-04 08:21

import apps.users.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_unique_userprofile_orcid_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userprofile',
            name='unique_nonblank_userprofile_orcid_id',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='orcid_id',
            field=apps.users.encryption.EncryptedCharField(blank=True, max_length=200),
        ),
    ]
