# Generated by Django 5.2.13 on 2026-08-21 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_type', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('running_title', models.CharField(blank=True, max_length=100)),
                ('abstract', models.TextField()),
                ('category', models.CharField(blank=True, max_length=255)),
                ('sub_category', models.CharField(blank=True, max_length=255)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('file_key', models.CharField(max_length=1024)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('cover_letter', models.TextField(blank=True)),
                ('no_funding', models.BooleanField(default=False)),
                ('funder', models.CharField(blank=True, max_length=255)),
                ('grant_no', models.CharField(blank=True, max_length=100)),
                ('no_competing', models.BooleanField(default=False)),
                ('competing', models.TextField(blank=True)),
                ('ethics_na', models.BooleanField(default=False)),
                ('ethics', models.TextField(blank=True)),
                ('data_statement', models.TextField(blank=True)),
                ('agreed_original', models.BooleanField(default=False)),
                ('agreed_not_under_review', models.BooleanField(default=False)),
                ('agreed_all_approve', models.BooleanField(default=False)),
                ('agreed_policies', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('revisions_requested', 'Revisions Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('published', 'Published')], default='submitted', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuscripts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManuscriptAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=10)),
                ('given_name', models.CharField(max_length=150)),
                ('family_name', models.CharField(max_length=150)),
                ('degree', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('orcid', models.CharField(blank=True, max_length=50)),
                ('corresponding', models.BooleanField(default=False)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='manuscripts.manuscript')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ManuscriptAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('country', models.CharField(blank=True, max_length=150)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='manuscripts.manuscriptauthor')),
            ],
        ),
        migrations.CreateModel(
            name='ManuscriptSupplementaryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_key', models.CharField(max_length=1024)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplementary_files', to='manuscripts.manuscript')),
            ],
        ),
    ]
