# Generated by Django 5.2.13 on 2026-08-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0002_plagiarismcheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plagiarismcheck',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='plagiarismcheck',
            name='error_message',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
