# Generated by Django 5.2.13 on 2026-08-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0003_remove_plagiarismcheck_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plagiarismcheck',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
