# Generated by Django 5.2.13 on 2026-08-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0004_alter_plagiarismcheck_error_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='plagiarismcheck',
            name='check_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
