# Generated by Django 5.2.13 on 2026-08-30 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0005_plagiarismcheck_check_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('desk_reject', 'Desk Reject'), ('accept', 'Accept'), ('minor', 'Minor Revision'), ('major', 'Major Revision'), ('reject', 'Reject')], max_length=20)),
                ('letter', models.TextField()),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions_made', to=settings.AUTH_USER_MODEL)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='manuscripts.manuscript')),
            ],
            options={
                'ordering': ['-decided_at'],
            },
        ),
    ]
