# Generated by Django 5.2.13 on 2026-09-02 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0006_decision'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManuscriptRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveSmallIntegerField()),
                ('file_key', models.CharField(max_length=1024)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('response_letter', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='manuscripts.manuscript')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
