# Generated by Django 5.2.13 on 2026-09-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0007_manuscriptrevision'),
        ('manuscripts', '0007_plagiarismcheck_corpus_document_id'),
    ]

    operations = [
    ]
