# Generated by Django 5.2.13 on 2026-09-03 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0008_merge_20260902_1454'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('allow', 'Allow through'), ('return', 'Return to author')], max_length=20)),
                ('note', models.TextField()),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
                ('acted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_actions', to=settings.AUTH_USER_MODEL)),
                ('manuscript', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screening_action', to='manuscripts.manuscript')),
            ],
        ),
    ]
