# Generated by Django 5.2.13 on 2026-09-04 04:02

from django.db import migrations, models


def backfill_published_at(apps, schema_editor):
    """
    Rows that reached 'published' before this field existed have no publication
    timestamp, and the discovery list orders on it. updated_at is the closest
    honest approximation — the publish was the last thing done to those rows.
    """
    Manuscript = apps.get_model('manuscripts', 'Manuscript')
    for manuscript in Manuscript.objects.filter(status='published', published_at__isnull=True):
        Manuscript.objects.filter(pk=manuscript.pk).update(published_at=manuscript.updated_at)


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0009_screeningaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_published_at, migrations.RunPython.noop),
    ]
