# Generated by Django 5.2.13 on 2026-09-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0009_screeningaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='specialty_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
