# Generated by Django 5.2.13 on 2026-09-04 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0010_manuscript_published_at'),
        ('manuscripts', '0010_manuscript_specialty_tags'),
    ]

    operations = [
    ]
