# Generated by Django 5.2.13 on 2026-09-15 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('role_change', 'Role change'), ('account_status', 'Account status'), ('invitation', 'Invitation'), ('settings_change', 'Settings change'), ('decision', 'Decision'), ('screening', 'Screening'), ('assignment', 'Assignment'), ('login_failure', 'Login failure')], db_index=True, max_length=32)),
                ('action', models.CharField(max_length=32)),
                ('summary', models.CharField(max_length=500)),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('actor_email', models.EmailField(blank=True, max_length=254)),
                ('target_name', models.CharField(blank=True, max_length=255)),
                ('target_email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(blank=True, max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
