# Generated by Django 5.2.13 on 2026-09-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='type',
            field=models.CharField(choices=[('role_change', 'Role change'), ('account_status', 'Account status'), ('invitation', 'Invitation'), ('settings_change', 'Settings change'), ('decision', 'Decision'), ('screening', 'Screening'), ('assignment', 'Assignment'), ('login_failure', 'Login failure'), ('security', 'Security')], db_index=True, max_length=32),
        ),
    ]
