# Generated by Django 5.2.13 on 2026-09-13 08:06
#
# The embedding columns were originally pgvector VectorField(384) with an HNSW
# index on ReviewerEmbedding. Matching moved to in-memory TF-IDF and 0002
# drops those tables/columns, so the types here are plain JSONField purely to
# keep migration history importable without the pgvector package.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manuscripts', '0011_merge_20260904_1553'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, unique=True)),
                ('embedding', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('embedding', models.JSONField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManuscriptEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField(null=True)),
                ('source_hash', models.CharField(max_length=64)),
                ('model_name', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manuscript', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='manuscripts.manuscript')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewerPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField(blank=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='ReviewerEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField(null=True)),
                ('source_hash', models.CharField(max_length=64)),
                ('model_name', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matching_embedding', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
