# Generated by Django 5.2.13 on 2026-09-15 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_threshold', models.PositiveSmallIntegerField(default=15)),
                ('high_threshold', models.PositiveSmallIntegerField(default=25)),
                ('exclude_quotes', models.BooleanField(default=True)),
                ('exclude_bibliography', models.BooleanField(default=True)),
                ('min_words', models.PositiveSmallIntegerField(default=8)),
                ('auto_flag', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'screening settings',
            },
        ),
    ]
