# Generated by Django 5.2.13 on 2026-09-03 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manuscripts', '0010_manuscript_specialty_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('submitted', 'Submitted')], default='invited', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('respond_by', models.DateTimeField()),
                ('due_days', models.PositiveSmallIntegerField()),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('coi_declared', models.BooleanField(default=False)),
                ('coi_note', models.TextField(blank=True)),
                ('decline_reason', models.CharField(blank=True, choices=[('conflict', 'Conflict of interest'), ('expertise', 'Outside my expertise'), ('unavailable', 'No capacity right now'), ('other', 'Another reason')], max_length=20)),
                ('decline_note', models.TextField(blank=True)),
                ('recused_at', models.DateTimeField(blank=True, null=True)),
                ('extension_requested_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('extension_reason', models.TextField(blank=True)),
                ('extension_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('granted', 'Granted'), ('refused', 'Refused')], max_length=20)),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to='manuscripts.manuscript')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-invited_at'],
                'unique_together': {('manuscript', 'reviewer')},
            },
        ),
    ]
