# Generated by Django 5.2.13 on 2026-09-03 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originality', models.PositiveSmallIntegerField()),
                ('technical', models.PositiveSmallIntegerField()),
                ('clarity', models.PositiveSmallIntegerField()),
                ('relevance', models.PositiveSmallIntegerField()),
                ('recommendation', models.CharField(choices=[('accept', 'Accept'), ('minor', 'Minor Revision'), ('major', 'Major Revision'), ('reject', 'Reject')], max_length=20)),
                ('summary', models.TextField()),
                ('strengths', models.TextField()),
                ('weaknesses', models.TextField()),
                ('confidential_to_editor', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='reviews.reviewassignment')),
            ],
        ),
    ]
