# Generated by Django 5.2.13 on 2026-09-12 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0011_merge_20260904_1553'),
        ('reviews', '0002_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviewassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='round',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='reviewassignment',
            unique_together={('manuscript', 'reviewer', 'round')},
        ),
    ]
