# Generated by Django 5.2.13 on 2026-09-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_reviewassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewassignment',
            name='authorship_conflict_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='match_breakdown',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='match_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='model_version',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
